### ISSUE TITLE
Errata readme.md 

### ISSUE THREAD

**Issue by iamnewspecies** [localytics/angular-chosen#116]
I think $resource should be there as a function parameter. 

Loading from a remote data source:
angular.module('App', ['ngResource', 'localytics.directives'])
.controller('BeerCtrl', function($scope,$resource) {
  $scope.beers = $resource('api/beers').query()
});

**Comment by leocaseiro** [comment]
Oh I see, you meant the **$resource** Dependency Injection?
Good catch!
I accepted your request #118.

Many thanks!
