### ISSUE TITLE
How well does this work with large arrays

### ISSUE THREAD

**Issue by simkessy** [localytics/angular-chosen#156]
I'm looking for an alternative to ui-select. I need something that can handle large arrays or datasets? Is this capable of handling something like 10k dropdown times?

**Comment by akotlar** [comment]
I've never used this with something quite so large, but of the libraries i've tried, including ui-select, it is the best performing.

**Comment by simkessy** [comment]
I'm currently trying Angular material's md-autocomplete. It has a lot of features I think are useful for dealing with large data like minimum input and remote loading of data but it triggers the on change event too often, even on clear, which is becoming a problem. I'll give this a shot tomorrow and see if it works for me. Thanks.

**Comment by leocaseiro** [comment]
You might want to use remote for your search, would that work for you?

**Comment by simkessy** [comment]
Hey, 

Yea I ended up pulling the data remotely and using minimum input so the dom wouldn't generate so many nodes. 

It seems to work pretty well.
