### ISSUE TITLE
Angular 1.5 compability - chosen object missing in functions scope

### ISSUE THREAD

**Issue by hobbysoldat** [localytics/angular-chosen#158]
Angular is getting a new version, and we updated already. All our plugins are already working, just the chosen plugin throws following error: 

`Cannot read property.results_none_found of undefined.`

in the disableWithMessage() function. The missing object is the chosen object, it seems like the chosen object is not defined in the functions scope. I am currently working on a solution since we want to continue using chosen. Has anybody experienced this issue yet or tried running with 1.5? 

My current Stack:

- Angular 1.5.0 rc2
- Jquery 2.2.0
- Chosen: Version supplied by Angular Chosen - v1.1.0.zip

**Comment by hobbysoldat** [comment]
Thanks for the commit, but this does just remove the error message and not restore the functionality. We had chosen working on the system with Angular 1.2.28 but now chosen seems deactivated. I am currently investigating the issue behind this.

**Comment by IWantPizza** [comment]
Oddly, in our situation the chosen dropdown was fully functional (with 0, 1 or many options) except for the errors. So this was just to suppress the errors.  I didn't PR because I know it's very quick and dirty. Had it been the only problem for anyone else they'd have probably fixed it by now. We're using Angular 1.4.9.

When I used console.log(chosen), it'd echo null about 3 times whilst loading the page before echoing the chosen object. I guess in your case you must always be getting null inside of that function?

**Comment by hobbysoldat** [comment]
Should have said that chosen is not working in my initial report. Yep, i am always getting null, but even with the guard clause the function is only called once, so there seems to be another breakage.

I now singled out the angular version that is breaking the chosen plugin. It's the update from Angular 1.5.0.rc0 to 1.5.0.rc1 ... will have a further look about what changed in there. If you change the version in the plunker it will work or break, strangely no error messages here ... 

https://plnkr.co/edit/Vvbv6TkbWEtiQybfeRO6?p=preview

**Comment by hobbysoldat** [comment]
Ahh ... I guess it might have something to do with that commit here ... https://github.com/angular/angular.js/commit/f7eab8d8fe8cadecaee425f0db0c74e48619310c
But still not sure how to fix it, looking into it.

**Comment by IWantPizza** [comment]
Does the fork from @akotlar solve this for you?

https://plnkr.co/edit/9BIpqVxJBu3K4mk7VCXw?p=preview

**Comment by hobbysoldat** [comment]
Hmm, the plunkr by @akotlar might be a more elegant solution than my hack ... setting the directive to terminal, did not know about this option, and am happy to apply it in my project. But I am not sure about the consequences, especially in collaboration with other directives, so i will leave the decision about how to fix it to the community. Will also create a pull request for the other solution.

**Comment by akotlar** [comment]
@hobbysoldat glad this worked for you. Just so you're aware, I made a pull request nearly 2 weeks ago with the solution #157 . Your #160 is an exact duplicate (except it doesn't introduce the fix into the coffee script version), please close to avoid confusion.

**Comment by hobbysoldat** [comment]
Thank you! Did not find this pull request, have closed mine as requested!

**Comment by akotlar** [comment]
Thanks! And for the support.

**Comment by leocaseiro** [comment]
Same issue with AngularJS 1.4.9 as reported at #155
