### ISSUE TITLE
Not working with AngularJS 1.4.9

### ISSUE THREAD

**Issue by arunghosh** [localytics/angular-chosen#161]
The chosen directive is not working with AngualJS 1.4.9. The ngModel.$render is not getting triggered.

` ngModel.$render = function() {
              origRender();
              return initOrUpdate();
  };`

I tried setting the directive priority to 1; the $render got triggered, but options list didn't bind.

Can any one help?

**Comment by leocaseiro** [comment]
Duplicated from #155
