### ISSUE TITLE
Witdh is Fixed

### ISSUE THREAD

**Issue by pachacutec** [localytics/angular-chosen#42]
Besides  I set the witdh:90% the directive convert to number XXXpx cause to multiple select not be responsive.

 <select chosen
                            multiple
                            data-placeholder="Select options"
                            allow-single-deselect="true"
                            no-results-text="'Add Project'"
                            ng-model="selectedGroup"
                            ng-options="group.name for group in groups"
                            style="width: 100%">

and the css is 
element.style {
      width: 294px;
}
.chosen-container {
position: relative;
display: inline-block;
vertical-align: middle;
font-size: 13px;
zoom: 1;
-webkit-user-select: none;
-moz-user-select: none;
user-select: none;
}

**Comment by ACDN** [comment]
Fantastic!

**Comment by yohendry** [comment]
@marcc1213 thanks dude!

**Comment by cailie** [comment]
@marcc1213 so helpful!

**Comment by leocaseiro** [comment]
Thanks @marcc1213 for help. Just define **width="'100%'"**

It worked: ```<select chosen width="'100%'">```

Here's a demo responsive for multiple chosen http://plnkr.co/edit/RMAe8c?p=preview

**Comment by wessamzaghloul** [comment]
when I added width="'100%'" the data-placeholder is not appearing and the default one is shown

**Comment by leocaseiro** [comment]
Hi @wessamzaghloul, could you please check if you are using single quotes? 

Like so:
`<select chosen width="'100%'">`

Check my example working: http://plnkr.co/edit/SBV6ut3xp9V63hnkGbhU?p=preview

Otherwise, please update the plunker with your code.

Thanks

**Comment by wessamzaghloul** [comment]
@leocaseiro thanks a lot for this fast reply I searched more and it only worked when I made it like this :
<select placeholder-text-multiple="'Search'" class="form-control" chosen="{width:'100%'}" multiple >

it is also not working in your plunker example your data-placeholder="Select options" but the resulted placeholder is the default one "Select Some Options"

thanks again

**Comment by leocaseiro** [comment]
Hi @wessamzaghloul. I'm sorry, I was so focus in the width, that I didn't realize you were mentioning about the placehoder. 

The `data-placeholder` is deprecated. 

You should use `placeholder-text-multiple` or `placeholder-text-single`.

**Comment by wessamzaghloul** [comment]
@leocaseiro  ahh ok sorry  it just worked before as data-placeholder before I add the  width="'100%'" that's why I added it here.

**Comment by leocaseiro** [comment]
@wessamzaghloul no problem! I'm glad you issue is working now :D

**Comment by mbsankar84** [comment]
tried for getting responsive window width conditionally and applied width in jquery.
$(document).ready(function () {
			if ($(window.width()) < 767) 
			{
$('.chosen-select').chosen({ width: "100%" }); 
}
			else {
				//alert($w)
				$('.chosen-select').chosen({ width: "50%" });
			}
I tried in css also using media query. but got error in chosen multi select it has come like normal paragraph with vertical scrollbar; attached the error screen. please suggest fix asap.
![chosen-width issue](https://user-images.githubusercontent.com/19747333/40537398-6fdb476a-602c-11e8-858a-52b5577e9486.PNG)

**Comment by leocaseiro** [comment]
Hi @mbsankar84, I'm not sure if I understand your issue.

Please open an issue following the ISSUE_TEMPLATE.

I believe it's an issue within the chosen library. 
Also, the chosen should not be on mobile as the mobile dropdown is the default behaviour.

**Comment by doitlikepruett** [comment]
Consider editing the title of this issue post from 'Witdh' to 'Width'. It will make it easier to find :). Took me a while. 

@leocaseiro All the examples in on the docs site (http://leocaseiro.github.io/angular-chosen) are broken in Chrome. Chrome version 66.0.3359.181 on Mac OS High Sierra. 

Example: http://leocaseiro.github.io/angular-chosen/#chosen-attributes

Chrome:
![screen shot 2018-05-29 at 3 12 46 pm](https://user-images.githubusercontent.com/16729315/40688618-96e76bb6-6353-11e8-9cb8-59d60aff2743.png)

Safari:
![screen shot 2018-05-29 at 3 17 57 pm](https://user-images.githubusercontent.com/16729315/40688622-9d2b6d06-6353-11e8-9d7b-56f0c2faebd2.png)


It is something with the width there as well. When viewed in Safari, everything shows up as expected. This might be coming from chosen itself but I can't tell yet. Certainly it has bearing on styling being applied to the select element, whether in a style attribute or through an inherited class.

**Comment by leocaseiro** [comment]
Hi @doitlikepruett, thank you.

1. I've updated the width

2. You're right, for some reason, the plunker embed is no longer working. It might be something with plunker, I'll investigate it. Thanks for reporting that.

If you click in the Open on plunker, works.

![screen shot 2018-05-30 at 1 00 10 pm](https://user-images.githubusercontent.com/940070/40696499-75bc30b4-6409-11e8-9bc1-126b568d1069.png)


See editor version on plunker working: https://plnkr.co/edit/a3oBYM?p=preview

Same source not working as embed: https://embed.plnkr.co/a3oBYM/

**Comment by nerrewton** [comment]
i make this and it worked !
`<div class="input-group" style="width:100% !important;">
                                        <select data-placeholder="Seleccione..." class="chosen-select" multiple>
                                            <option>Seleccione ...</option>
                                            <option>Contacto 1</option>
                                            <option>Contacto 2</option>
                                        </select>
                                        </div>`
