### ISSUE TITLE
<optgroup> Support?

### ISSUE THREAD

**Issue by Siyfion** [localytics/angular-chosen#47]
Assuming that I have a collection of elements with a group property, is there a way to use 'ng-options' in such a way that it will produce correct '<optgroup>' tags? As I can't think of a way of doing this...

**Comment by dkavanagh** [comment]
Sort of... doesn't honor "as" and uses index as value instead.

**Comment by webeng** [comment]
The "group by" worked for me.

**Comment by Bent10** [comment]
You can use "group by" expression

```json
{
  "teams": [
    {"name": "Johan", "email": "johan@mail.com", "group": "one"},
    {"name": "Mala", "email": "mala@mail.com", "group": "two"},
    {"name": "Saimin", "email": "saimin@mail.com", "group": "one"},
    {"name": "Dolah", "email": "doll@mail.com", "group": "three"},
    {"name": "Abah", "email": "abah@mail.com", "group": "three"}
  ]
}
```

then use 

```html
ng-options="t.name group by t.group for t in teams"
```

**Comment by leocaseiro** [comment]
Thanks @robinfhu @Bent10 

I've made a plunkr for it: http://plnkr.co/edit/j0yIif?p=preview
