### ISSUE TITLE
the dropdown doesn't refresh after a promise is updated with value. 

### ISSUE THREAD

**Issue by kathygit** [localytics/angular-chosen#82]
I tried to use promise and the drop down list says "no result" even after the result is comback. 
I tested with this sample code:

                    simulateAjax = function(result) {
                        var deferred, fn;

                        deferred = $q.defer();
                        fn = function() {
                            return deferred.resolve(result);
                        };
                        $timeout(fn, 3000);
                        return deferred.promise;
                    };
                    simulateAjax(['grooo', 'wowowowow', 'lakakalakakl', 'yadayada', 'insight', 'delve', 'synergy'])
                        .then(function(result) {
                            scope.optionsFromQuery = result;
                    });

**Comment by nextriot** [comment]
@kirliam +1 for this to be merged. Fixed the issue on my end too. Thanks!

**Comment by gaui** [comment]
FYI it got merged. #95
